### ISSUE TITLE
hubuco v3 ajax/json

### ISSUE THREAD

**Issue by leowebguy** [hubuco/api#1]
Hi Tamas,

I'm using this verifier (with a few changes of course) hosted on a web server, then I run as a PHP... /usr/bin/php /somefolder/verifier.php but it is taking forever because call is being made through hubuco.com/api/v2 using file_get_contents such and such...

Can you please provide directions on how to make the call using hubuco.com/api/v3 via POST/AJAX + JSON ... I've read the page https://www.hubuco.com/api can't figure it out.

Tks!

**Comment by tamas-hamszabo** [comment]
Hi,

Thank you for your patience. Find docs for v3 here:
https://github.com/hubuco/real-time-email-verification-api-v3

**Comment by leowebguy** [comment]
awesome!
